### ISSUE TITLE
Invalid Configuration For Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch

### ISSUE THREAD

**Issue by rowie1** [esphome-devices/esphome-devices#101]
I'm unable to create a valid configuration file from this template using ESPHome in Home Assistant. The "LOW", "MEDIUM" & "HIGH" entries in the template cause an error. 

<img width="1125" alt="Screen Shot 2021-05-27 at 6 57 30 am" src="https://user-images.githubusercontent.com/69198519/119733640-f8a8bd00-beb8-11eb-8731-c7a89e6cec83.png">

**Comment by jkelly73** [comment]
I too have this problem... Any pointers on how to resolve it?
