### ISSUE TITLE
Why don't configs on esphome-devices.com match Github?

### ISSUE THREAD

**Issue by flyize** [esphome-devices/esphome-devices#156]
For example, the config listed here:
https://www.esphome-devices.com/devices/TreatLife-DS03

Does not match the config listed here:
https://github.com/esphome-devices/esphome-devices/blob/main/src/docs/devices/TreatLife-DS03/index.md

What am I missing?

**Comment by tekmaven** [comment]
Sorry, I don't see a difference in the two documents?

**Comment by flyize** [comment]
Either I'm crazy or the last two commits were not showing. But I agree that they match now.
