### ISSUE TITLE
Lohas 100W bulbs (RGBCW) aren't esps anymore

### ISSUE THREAD

**Issue by jeffeb3** [esphome-devices/esphome-devices#182]
I opened one up. It has this microcontroller instead:

BEKEN
BK7231N
U117YDC

esp device page: https://www.esphome-devices.com/devices/Lohas-RGBCW-100W

It still recommends the tuya app (but I didn't try to install it). I did try to flash it with tuya convert. That complained that the tuya device was too new and used new encryption (which is possible), but even if it had gotten that far, there is no esp8266 in there.

It seems like there should either be a warning, or that page should be removed.

**Comment by tekmaven** [comment]
I think a warning would be preferred, because people still need that page as a reference.  You can click the "Edit the page" link and add the warning.

**Comment by jeffeb3** [comment]
That makes sense. I looked for a minute and didn't see another warning to give me a format, but I made a PR #183 

Thanks.

**Comment by tekmaven** [comment]
Thanks for the contribution!
