### ISSUE TITLE
BlitzWolf BW-SHP2

### ISSUE THREAD

**Issue by Strixx76** [esphome-devices/esphome-devices#200]
I have thre of these working with ESPHome and flashed with tuya-converter that I bought about a year ago. But last month I bought  three new devices from Banggood that failed flashing. I opened them up for serial flashing but discovered that they did not contain a ESP-chip.

I then found the following:

> WARNING: New Tuya devices have replaced their Wi-Fi module with one incompatible with Tasmota!!!

[BlitzWolf BW-SHP2 Power Monitoring Plug](https://templates.blakadder.com/blitzwolf_SHP2.html)

Should there maybe be the same warning on this page?

**Comment by tekmaven** [comment]
To help us update the page, follow the "Edit the page on Github" link on the bottom and add the warning.
