### ISSUE TITLE
Url: Kogan RGB + Cool & Warm White 2m LED Strip

### ISSUE THREAD

**Issue by sumur1au** [esphome-devices/esphome-devices#216]
Can you please correct the URL for Kogan Led strip ?

Current Link: [https://www.esphome-devices.com/devices/Kogan-RGB+CoolandWarm-White-2m-LED-Strip/](https://www.esphome-devices.com/devices/Kogan-RGB+CoolandWarm-White-2m-LED-Strip/)

Correct Link: [https://www.esphome-devices.com/devices/Kogan-RGB+Cool&Warm-White-2m-LED-Strip](https://www.esphome-devices.com/devices/Kogan-RGB+Cool&Warm-White-2m-LED-Strip)

**Comment by sumur1au** [comment]
@tekmaven This is the current link: [https://www.esphome-devices.com/devices/Kogan-RGB+CoolandWarm-White-2m-LED-Strip/ ](https://www.esphome-devices.com/devices/Kogan-RGB+CoolandWarm-White-2m-LED-Strip/ )which shows an error.

**Comment by tekmaven** [comment]
I'm not sure I phrased my question well, sorry.  Where is the broken link?  I understand the incorrect URL, but how do I find the page that has the original link?

**Comment by sumur1au** [comment]
@tekmaven Sorry about that, it is on the au page of ESPhome devices: 
[https://www.esphome-devices.com/standards/au](https://www.esphome-devices.com/standards/au)
