### ISSUE TITLE
Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch sequencing

### ISSUE THREAD

**Issue by greengumbyaus** [esphome-devices/esphome-devices#259]
Had issues with the fan relay sequencing for this device:  https://github.com/esphome-devices/esphome-devices/blob/main/src/docs/devices/Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch/index.md

The correct relay sequence is:
fan speed 1:
relay1: on
relay2: off
relay3: off

fan speed 2:
relay1: on
relay2: off
relay3: on

fan speed 3:
relay1: on
relay2: on
relay3: on

Needed to fix this up in the output template, binary sensor gpio and switch template.

**Comment by nagyrobi** [comment]
Fix in https://github.com/esphome/esphome-devices/pull/389
