### ISSUE TITLE
Mi-Desklamp-1S

### ISSUE THREAD

**Issue by danielducu** [esphome-devices/esphome-devices#300]
Compiling and uploading the firmware is flawless but lamp won't turn on... it's dead. Tried this on two lamps and they both died. Logs show this in a loop:

ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
E (374) cpu_start: Running on single core variant of a chip, but app is built with multi-core support.
E (374) cpu_start: Check that CONFIG_FREERTOS_UNICORE is enabled in menuconfig

abort() was called at PC 0x40083051 on core 0

Backtrace:0x40083aa1:0x3ffe3b300x4008c8b1:0x3ffe3b50 0x40091f81:0x3ffe3b70 0x40083051:0x3ffe3bf0 0x40079053:0x3ffe3c40  |<-CORRUPTED

**Comment by mjbogusz** [comment]
This is due to the lamp using a single-core ESP32 chip, which results in some challenges... see https://github.com/esphome/issues/issues/1560

I'll try posting my mostly-working config as a PR soon.
