### ISSUE TITLE
Gosund WP3

### ISSUE THREAD

**Issue by bens545** [esphome-devices/esphome-devices#32]
I have a few of the Gosund WP3 outlets and I noticed that the pins don't match with the existing WP3 config.  I found the right pins for my plugs, and I'm happy to share them.  

Let me know if you want me to open PR that modifies, or appends to the existing config, or to create a new config.

**Comment by tekmaven** [comment]
Please open a PR!  I actually updated the existing pinouts based on my devices, so maybe there are different revisions, or maybe I just got mine wrong.  I can test also on my device if you share a PR.

**Comment by tekmaven** [comment]
Going to close, will look out for the PR.

I also own this product and may get around to refining the config a little bit soon - I have not incorporated it into a project yet.
