### ISSUE TITLE
Sonoff-Mini-Relay - Board Type

### ISSUE THREAD

**Issue by thewishy** [esphome-devices/esphome-devices#64]
Hi,

I *think* Sonoff-Mini-Relay.md provides the wrong board type. I had a lot of issue with crashing and disconnections (Both Home Assistant and ESPHome log collection) when the board type "board: esp01_1m" was used. https://esphome.io/devices/sonoff.html lists the board type as "board: esp8285", and since switching to this configuration everything has been working fine.

My level of confidence with this being the "Right answer" isn't high. It worked for me, and matches the ESPHome website, but I have little experience with ESPHome and would therefore rather raise an issue for validation than modify the configs directly. 

ESPHome version 1.15.3
Home Assistant version 2021.1.5

**Comment by tekmaven** [comment]
I do not own this device to check unfortunately!  

If you would like to submit a PR that edits that page, go right ahead.  We can change this default value and you can add a note if you think its needed!

**Comment by thewishy** [comment]
PR created
