### ISSUE TITLE
Search not working on website

### ISSUE THREAD

**Issue by jesserockz** [esphome-devices/esphome-devices#99]
I see a 403 forbidden whenever I try to use the search

**Comment by tekmaven** [comment]
Sorry @jesserockz!  The search feature ended up being very popular and we overran our free plan from the search engine provider Algolia.  I have a request in with them to raise our limits under their "Algolia for Open Source" initiative, which I hope to hear back soon on.  If Algolia does not come through soon, I will try to switch to a different search engine.

**Comment by tekmaven** [comment]
Algolia agreed to put us on the open source plan :) and search results are back.

**Comment by jesserockz** [comment]
I guess that is a good thing it went over the limits. It means it is being used =)
